import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us — GTA Scrub Commercial Cleaning",
  description: "Learn about GTA Scrub, the GTA's premier commercial cleaning company. Photo-verified CleanCheck reports, insured and bonded.",
    alternates: { canonical: "https://gtascrub.com/about" },
};

export default function AboutPage() {
  return (
    <>
      <section className="relative py-24 bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url(/images/gta-scrub-commercial-cleaning-hero-aboutus.png)" }}>
        <div className="absolute inset-0 bg-gradient-to-r from-gray-50/95 via-gray-50/80 to-gray-50/60" />
        <div className="container mx-auto px-6 relative"><div className="text-center mb-16"><span className="inline-block text-sm font-bold text-brand-ink bg-brand-pale px-5 py-2 rounded-full mb-5 border border-brand/20">About</span><h1 className="text-4xl lg:text-5xl font-black text-brand-ink tracking-tight">About GTA Scrub</h1></div></div></section>
      <section className="py-16 bg-white"><div className="container mx-auto px-6 max-w-3xl"><p className="text-lg text-gray-600 leading-relaxed mb-6">GTA Scrub is a Brampton-based commercial cleaning company serving the entire Greater Toronto Area. Founded with a simple mission: prove every clean with photo-verified evidence so businesses never have to wonder if their office was actually cleaned.</p><p className="text-lg text-gray-600 leading-relaxed mb-6">Our CleanCheck system photographs every cleaned area and scores it against a rigorous 90-point checklist. You see the proof before you pay. It&apos;s cleaning accountability, guaranteed.</p></div></section>
      <section className="py-20 bg-gray-50"><div className="container mx-auto px-6"><div className="grid grid-cols-2 md:grid-cols-4 gap-6"><div className="text-center p-8 bg-white rounded-3xl"><div className="text-4xl md:text-5xl font-black text-brand-ink mb-2">5,000+</div><div className="text-sm font-bold text-gray-500">Spaces Cleaned</div></div><div className="text-center p-8 bg-white rounded-3xl"><div className="text-4xl md:text-5xl font-black text-brand-ink mb-2">14</div><div className="text-sm font-bold text-gray-500">Cities in the GTA</div></div><div className="text-center p-8 bg-white rounded-3xl"><div className="text-4xl md:text-5xl font-black text-brand-ink mb-2">4.9/5</div><div className="text-sm font-bold text-gray-500">Average Rating</div></div><div className="text-center p-8 bg-white rounded-3xl"><div className="text-4xl md:text-5xl font-black text-brand-ink mb-2">99.8%</div><div className="text-sm font-bold text-gray-500">Satisfaction Rate</div></div></div></div></section>
      <section className="py-16 bg-white"><div className="container mx-auto px-6 max-w-3xl"><h2 className="text-3xl font-black text-brand-ink mb-8">Why Choose GTA Scrub</h2><ul className="space-y-4"><li className="flex items-start gap-3 text-gray-700"><svg className="w-5 h-5 text-[#70cf36] mt-0.5 shrink-0" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg><span>Photo-verified CleanCheck reports with every visit</span></li><li className="flex items-start gap-3 text-gray-700"><svg className="w-5 h-5 text-[#70cf36] mt-0.5 shrink-0" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg><span>Free demo clean — try us risk-free before committing</span></li><li className="flex items-start gap-3 text-gray-700"><svg className="w-5 h-5 text-[#70cf36] mt-0.5 shrink-0" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg><span>No long-term contracts. Flexible scheduling.</span></li><li className="flex items-start gap-3 text-gray-700"><svg className="w-5 h-5 text-[#70cf36] mt-0.5 shrink-0" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg><span>$2M liability insurance and WSIB coverage</span></li></ul></div></section>
      <section className="py-24 bg-brand-ink text-center"><div className="container mx-auto px-6"><h2 className="text-4xl md:text-5xl font-black text-brand mb-6">Ready for a Spotless Space?</h2><p className="text-lg text-gray-300 mb-10 max-w-2xl mx-auto">Get your free quote within 2 hours.</p><Link href="/contact" className="bg-brand text-brand-ink px-8 py-4 rounded-2xl font-bold inline-block hover:bg-brand-active transition-colors shadow-lg shadow-brand/30">Get Started</Link></div></section>
    </>
  );
}
